[package]
name = "allcast-receiver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "allcast-receiver"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
gstreamer.workspace = true
gio = "0.20"
socket2 = "0.5"
tracing.workspace = true
tracing-subscriber.workspace = true
allcast-telemetry.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream = "0.1"
