[package]
name = "share-screen-sender"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "share-screen-sender"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
gstreamer.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
