[package]
name = "allcast-sender"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "allcast-sender"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
gstreamer.workspace = true
gstreamer-video = "0.23"
tracing.workspace = true
tracing-subscriber.workspace = true
allcast-telemetry.workspace = true
tonic.workspace = true
tokio.workspace = true
